version: "3.9"
services:
  server_app_test:
    container_name: server
    build:
      context: .
      dockerfile: dockers/Dockerfile.server_app_test
    ports:
      - "127.0.0.1:3001:3001"
    depends_on:
      test_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f 127.0.0.1:3001/api/health_check || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=3001
      - DATABASE_URL=postgresql://postgres:PASSWORD@test_db:5432/postgres
  test_db:
    build:
      context: .
      dockerfile: dockers/Dockerfile.test_db
    ports:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=PASSWORD psql --port=5432 --user=postgres --host=0.0.0.0 \
-XtAc \"SELECT 1 FROM pg_database WHERE datname='postgres'\"" ]
      interval: 1s
      timeout: 10s
      retries: 10

