version: "3.9"
services:
  server_dev:
    build:
      context: .
      dockerfile: dockers/Dockerfile.server_dev
    ports:
      - "3000:8000"
    depends_on:
      test_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f 127.0.0.1:8000" ]
      interval: 5s
      timeout: 10s
      retries: 5
  test_db:
    build:
      context: .
      dockerfile: dockers/Dockerfile.test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=PASSWORD psql --port=5432 --user=postgres --host=0.0.0.0 \
-XtAc \"SELECT 1 FROM pg_database WHERE datname='postgres'\"" ]
      interval: 1s
      timeout: 10s
      retries: 10
  app_test:
    build:
      context: .
      dockerfile: dockers/Dockerfile.app_test
    ports:
      - "8000:8000"
    depends_on:
      server_dev:
        condition: service_healthy