FROM rustlang/rust:nightly-buster as BUILD
COPY .. .
RUN cargo +nightly build --release --package server --features dev,mock_email
EXPOSE 3000

FROM alpine
COPY --from=BUILD ./target/release/server ./target/release/server
ENTRYPOINT ["./target/release/server"]


