# Must be run from crate root
# docker build -f ./dockers/Dockerfile.server_app_test .

FROM rustlang/rust:nightly-bullseye as CACHE
WORKDIR poetshuffle
RUN mkdir -p crates/entity/src && \
    echo "" > crates/entity/src/mod.rs && \
    mkdir -p crates/migration/src && \
    echo "" > crates/migration/src/lib.rs && \
    mkdir -p crates/server/src && \
    echo "fn main() {}" > crates/server/src/main.rs
COPY ./crates/server/Cargo.toml ./crates/server
COPY ./crates/entity/Cargo.toml ./crates/entity
COPY ./crates/migration/Cargo.toml ./crates/migration
RUN cd crates/server && cargo fetch

FROM rustlang/rust:nightly-bullseye as BUILD
COPY --from=CACHE /usr/local/cargo /usr/local/cargo
COPY .. ./poetshuffle/
WORKDIR poetshuffle
RUN cargo +nightly build --release --package server --features app-test

FROM debian:latest
COPY --from=BUILD /poetshuffle/target/release/server ./bin
RUN apt-get update
RUN apt-get install -y curl
EXPOSE 3001
ENTRYPOINT ["server"]


