//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "poems"
    }
}

use async_graphql::*;
#[derive(
Clone, Debug, PartialEq, Serialize, Deserialize, DeriveModel, DeriveActiveModel, SimpleObject,
)]
#[graphql(concrete(name = "Poem", params()))]
pub struct Model {
    pub poem_uuid: Uuid,
    pub originator_uuid: Uuid,
    pub creation_ts: DateTimeWithTimeZone,
    pub set_uuid: Uuid,
    pub banter_uuid: Option<Uuid>,
    pub title: String,
    pub idx: i32,
    pub last_edit_ts: Option<DateTimeUtc>,
    pub approved: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    PoemUuid,
    OriginatorUuid,
    CreationTs,
    SetUuid,
    BanterUuid,
    Title,
    Idx,
    LastEditTs,
    Approved,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    PoemUuid,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Banters,
    Users,
    Sets,
    Comments,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::PoemUuid => ColumnType::Uuid.def(),
            Self::OriginatorUuid => ColumnType::Uuid.def(),
            Self::CreationTs => ColumnType::TimestampWithTimeZone.def(),
            Self::SetUuid => ColumnType::Uuid.def(),
            Self::BanterUuid => ColumnType::Uuid.def().null(),
            Self::Title => ColumnType::String(Some(100u32)).def(),
            Self::Idx => ColumnType::Integer.def(),
            Self::LastEditTs => ColumnType::Timestamp.def().null(),
            Self::Approved => ColumnType::Boolean.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Banters => Entity::belongs_to(super::banters::Entity)
                .from(Column::BanterUuid)
                .to(super::banters::Column::BanterUuid)
                .into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::OriginatorUuid)
                .to(super::users::Column::UserUuid)
                .into(),
            Self::Sets => Entity::belongs_to(super::sets::Entity)
                .from(Column::SetUuid)
                .to(super::sets::Column::SetUuid)
                .into(),
            Self::Comments => Entity::has_many(super::comments::Entity).into(),
        }
    }
}

impl Related<super::banters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Banters.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sets.def()
    }
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
