//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "invitations"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub invite_uuid: Uuid,
    pub invitor_uuid: Uuid,
    pub invitee_email: String,
    pub creation_ts: DateTimeWithTimeZone,
    pub fufilled: bool,
    pub fufilled_ts: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    InviteUuid,
    InvitorUuid,
    InviteeEmail,
    CreationTs,
    Fufilled,
    FufilledTs,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    InviteUuid,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::InviteUuid => ColumnType::Uuid.def(),
            Self::InvitorUuid => ColumnType::Uuid.def(),
            Self::InviteeEmail => ColumnType::String(None).def(),
            Self::CreationTs => ColumnType::TimestampWithTimeZone.def(),
            Self::Fufilled => ColumnType::Boolean.def(),
            Self::FufilledTs => ColumnType::TimestampWithTimeZone.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::InvitorUuid)
                .to(super::users::Column::UserUuid)
                .into(),
        }
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
