//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "poems"
    }
}

use async_graphql::*;
#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, SimpleObject)]
#[graphql(concrete(name = "Poem", params()))]
pub struct Model {
    pub poem_uuid: Uuid,
    pub originator_uuid: Uuid,
    pub creation_ts: DateTimeWithTimeZone,
    pub set_uuid: Uuid,
    pub banter_uuid: Option<Uuid>,
    pub title: String,
    pub idx: i32,
    pub part_of_poetshuffle: bool,
    pub editor_uuid: Option<Uuid>,
    pub approved: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    PoemUuid,
    OriginatorUuid,
    CreationTs,
    SetUuid,
    BanterUuid,
    Title,
    Idx,
    PartOfPoetshuffle,
    EditorUuid,
    Approved,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    PoemUuid,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Banter,
    Users2,
    Users1,
    Sets,
    Comments,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::PoemUuid => ColumnType::Uuid.def(),
            Self::OriginatorUuid => ColumnType::Uuid.def(),
            Self::CreationTs => ColumnType::TimestampWithTimeZone.def(),
            Self::SetUuid => ColumnType::Uuid.def(),
            Self::BanterUuid => ColumnType::Uuid.def().null(),
            Self::Title => ColumnType::String(Some(100u32)).def(),
            Self::Idx => ColumnType::Integer.def(),
            Self::PartOfPoetshuffle => ColumnType::Boolean.def(),
            Self::EditorUuid => ColumnType::Uuid.def().null(),
            Self::Approved => ColumnType::Boolean.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Banter => Entity::belongs_to(super::banters::Entity)
                .from(Column::BanterUuid)
                .to(super::banters::Column::BanterUuid)
                .into(),
            Self::Users2 => Entity::belongs_to(super::users::Entity)
                .from(Column::EditorUuid)
                .to(super::users::Column::UserUuid)
                .into(),
            Self::Users1 => Entity::belongs_to(super::users::Entity)
                .from(Column::OriginatorUuid)
                .to(super::users::Column::UserUuid)
                .into(),
            Self::Sets => Entity::belongs_to(super::sets::Entity)
                .from(Column::SetUuid)
                .to(super::sets::Column::SetUuid)
                .into(),
            Self::Comments => Entity::has_many(super::comments::Entity).into(),
        }
    }
}

impl Related<super::banters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Banter.def()
    }
}

impl Related<super::sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sets.def()
    }
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
