//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use super::sea_orm_active_enums::SetStatus;
use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "sets"
    }
}

use async_graphql::*;
#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, SimpleObject)]
#[graphql(name = "Set")]
pub struct Model {
    pub set_uuid: Uuid,
    pub creation_ts: DateTimeWithTimeZone,
    pub collection_title: String,
    pub originator_uuid: Uuid,
    pub set_status: SetStatus,
    pub collection_link: String,
    pub editor_uuid: Option<Uuid>,
    pub approved: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    SetUuid,
    CreationTs,
    CollectionTitle,
    OriginatorUuid,
    SetStatus,
    CollectionLink,
    EditorUuid,
    Approved,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    SetUuid,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Users2,
    Users1,
    Poems,
    Intros,
    Comments,
    SetOptions,
    Orders,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::SetUuid => ColumnType::Uuid.def(),
            Self::CreationTs => ColumnType::TimestampWithTimeZone.def(),
            Self::CollectionTitle => ColumnType::String(Some(100u32)).def(),
            Self::OriginatorUuid => ColumnType::Uuid.def(),
            Self::SetStatus => SetStatus::db_type(),
            Self::CollectionLink => ColumnType::String(Some(250u32)).def(),
            Self::EditorUuid => ColumnType::Uuid.def().null(),
            Self::Approved => ColumnType::Boolean.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users2 => Entity::belongs_to(super::users::Entity)
                .from(Column::EditorUuid)
                .to(super::users::Column::UserUuid)
                .into(),
            Self::Users1 => Entity::belongs_to(super::users::Entity)
                .from(Column::OriginatorUuid)
                .to(super::users::Column::UserUuid)
                .into(),
            Self::Poems => Entity::has_many(super::poems::Entity).into(),
            Self::Intros => Entity::has_many(super::intros::Entity).into(),
            Self::Comments => Entity::has_many(super::comments::Entity).into(),
            Self::SetOptions => Entity::has_many(super::set_options::Entity).into(),
            Self::Orders => Entity::has_many(super::orders::Entity).into(),
        }
    }
}

impl Related<super::poems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Poems.def()
    }
}

impl Related<super::intros::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Intros.def()
    }
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::set_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SetOptions.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
